# Generated by Django 5.0 on 2025-12-03 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='氏名')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
            ],
        ),
    ]
